// @ts-check
// A build tree into publishable packages: the manifest, the binaries, the README, and the index.js that
// exports the getBinaryPath resolve.js calls. Builds nothing, and refuses a binary the build did not leave.

import { chmodSync, copyFileSync, cpSync, existsSync, mkdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { buildTree, packageDir } from './layout.js';
import { packagesFor } from './packages.js';
import { binaryFilename } from './targets.js';

/**
 * The module a platform package exports, generated so the binaries it names are the ones staged beside it.
 * CommonJS on purpose: it is required by whatever a component's loader happens to be.
 *
 * @param {Record<string, string>} files `shipsAs` to the filename on disk.
 * @param {readonly string[]} extraDirs Directories shipped beside `bin/`, each given its own accessor.
 */
export function indexModule(files, extraDirs) {
	const accessors = extraDirs.map(
		(dir) => `,
  ${accessorName(dir)}() {
    return path.join(__dirname, ${JSON.stringify(dir)});
  }`
	);
	return `const path = require('path');

// Generated by @helpfulsoftwarecrew/harper-binary-kit. Edits are overwritten by the next staging.
const BINARIES = ${JSON.stringify(files, null, 2)};

module.exports = {
  // Asked by the name the binary ships under, never by a path: where this package puts its files is this
  // package's business, and a caller that computes the path is computing it from a layout that can change.
  getBinaryPath(name = ${JSON.stringify(Object.keys(files)[0] ?? '')}) {
    const file = BINARIES[name];
    if (!file) throw new Error(\`Unknown binary: \${name}. This package ships: \${Object.keys(BINARIES).join(', ')}\`);
    return path.join(__dirname, 'bin', file);
  }${accessors.join('')}
};
`;
}

/** `share/system-probe` becomes `getShareSystemProbeDir`. One rule, so a consumer can predict the name. */
export function accessorName(/** @type {string} */ dir) {
	const parts = dir
		.split('/')
		.filter(Boolean)
		.map((part) => part.replace(/[^A-Za-z0-9]+(.)?/g, (_, next) => (next ? next.toUpperCase() : '')));
	return `get${parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join('')}Dir`;
}

/**
 * Stage one package: binaries, extra directories, manifest, index, README.
 *
 * @param {object} options
 * @param {string} options.root Repo root; the build tree and `npm/` are both under it.
 * @param {import('./packages.js').PlatformPackage} options.pkg
 * @param {string} options.version
 * @param {object} options.manifest Fields merged into the generated package.json: repository, author, licence.
 * @param {(pkg: import('./packages.js').PlatformPackage) => string} [options.describe] The manifest's `description`.
 * @param {(pkg: import('./packages.js').PlatformPackage) => string} [options.readme] The consumer's own README.
 * @returns {string} The directory it staged into.
 */
export function stagePackage({ root, pkg, version, manifest, describe = defaultDescription, readme }) {
	const dir = packageDir(root, pkg.dirName);
	const tree = buildTree(root, pkg.target.name);
	mkdirSync(join(dir, 'bin'), { recursive: true });

	for (const binary of pkg.binaries) {
		const file = binaryFilename(binary.shipsAs, pkg.target);
		const from = join(tree.bin, file);
		if (!existsSync(from)) {
			throw new Error(
				`${pkg.name} carries ${file} and there is nothing at ${from}. Run the build for ${pkg.target.name} first; ` +
					`staging around a missing binary publishes a package nothing can run.`
			);
		}
		const to = join(dir, 'bin', file);
		copyFileSync(from, to);
		// npm preserves the mode it packed, so a binary staged without this installs unexecutable.
		chmodSync(to, 0o755);
		// NTFS cannot carry the bit, so a POSIX package staged on Windows packs a binary nothing can run and
		// reports success. The mode is read back rather than the chmod trusted.
		if (pkg.target.os !== 'windows' && (statSync(to).mode & 0o111) !== 0o111) {
			throw new Error(
				`${pkg.name} staged ${file} and this filesystem did not keep its executable bit. npm packs the ` +
					`mode it finds, so the published package would install a binary nothing can run. Stage ` +
					`${pkg.target.name} on a host whose filesystem carries the bit.`
			);
		}
	}

	for (const extra of pkg.extraDirs) {
		const from = join(tree.root, extra);
		if (!existsSync(from)) {
			throw new Error(
				`${pkg.name} ships ${extra} and there is nothing at ${from}. A binary that needs those files starts, ` +
					`answers \`version\`, and does nothing, which is worse than failing to start.`
			);
		}
		cpSync(from, join(dir, extra), { recursive: true });
	}

	writeFileSync(
		join(dir, 'package.json'),
		`${JSON.stringify(
			{
				name: pkg.name,
				version,
				description: describe(pkg),
				main: 'index.js',
				// What npm filters the install on. Wrong here and the package installs nowhere, silently.
				os: [pkg.target.npmOs],
				cpu: [pkg.target.npmCpu],
				...manifest,
				files: ['bin/', 'index.js', 'README.md', ...pkg.extraDirs.map((extra) => `${extra}/`)],
			},
			null,
			'\t'
		)}\n`
	);

	const files = Object.fromEntries(pkg.binaries.map((b) => [b.shipsAs, binaryFilename(b.shipsAs, pkg.target)]));
	writeFileSync(join(dir, 'index.js'), indexModule(files, pkg.extraDirs));
	if (readme) writeFileSync(join(dir, 'README.md'), readme(pkg));
	return dir;
}

/** @param {import('./packages.js').PlatformPackage} pkg */
function defaultDescription(pkg) {
	const names = pkg.binaries.map((b) => b.shipsAs);
	const listed = names.length < 2 ? names.join('') : `${names.slice(0, -1).join(', ')} and ${names.at(-1)}`;
	return `${listed} for ${pkg.target.os} ${pkg.target.arch}`;
}

/**
 * Stage every package for the targets asked for.
 *
 * @param {object} options
 * @param {string} options.root @param {any} options.config @param {string} options.version
 * @param {readonly import('./targets.js').Target[]} options.targets
 * @param {string} [options.only] One package's `dirName`, for staging a single one.
 * @returns {string[]} The names staged. Empty is a caller's mistake, never a success.
 */
export function stageAll({ root, config, version, targets, only }) {
	const staged = [];
	for (const on of targets) {
		for (const pkg of packagesFor(config, on)) {
			if (only && pkg.dirName !== only) continue;
			stagePackage({
				root,
				pkg,
				version,
				manifest: config.manifest ?? {},
				describe: config.describe,
				readme: config.readme,
			});
			staged.push(pkg.name);
		}
	}
	// A filter that matched nothing would otherwise read as success, and the publish after it would find nothing.
	if (staged.length === 0) {
		throw new Error(
			only
				? `no package named "${only}" among the targets given (${targets.map((t) => t.name).join(', ')})`
				: 'no packages were staged: the target list is empty, or no variant carries a binary on any of them'
		);
	}
	return staged;
}
